# Generated by Django 3.0.3 on 2020-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_auto_20200707_1120"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="movies",
            field=models.CharField(choices=[("sd", "sd")], default="", max_length=100),
        ),
    ]
