# Generated by Django 3.0.3 on 2020-07-07 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0004_remove_rating_movie"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movies",
                to="ratings.Movie",
            ),
            preserve_default=False,
        ),
    ]
