# Generated by Django 3.0.3 on 2020-07-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0005_rating_movie"),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="movie",),
    ]
